- src/Makefile
- src/bootstrap.js
- src/modules/menu.js
- src/modules/page.js
It frequently occurs to me that the "Goto, Fill And Submit"-feature doesn't work as expected. It will only wait for _any_ of the currently open tabs to load and then fill in credentials for that particular tab. That's of course problematic whenever there are several tabs loading at the time when the "Goto, Fill And Submit" is fired. 
The proposed patch is far from the most elegant solution and it might still be problematic in some cases. But it works for me. (Especially, because I'm not using the preference "Try to auto fill page forms".)
> Tab sensitive load event handling.

- README.md
Expanded on the existing OS X troubleshooting steps.  Included steps to address a bug in pass as of version 1.6.5. Refer to Gitter conversation on Aug. 28-29, 2015 for more information.
> update OS X troubleshooting steps

- src/modules/pass.js
This resolves https://github.com/jvenant/passff/issues/115, where auto fill was incorrectly using the directory name as username
> Do not add items to the menu if they are not leafs

- src/chrome/locale/de-DE/preferences.dtd
This commit adds two strings to the German translation,
* enter-behavior
* enter-behavior-tooltip.
This probably fixes a bug where the preferences window cannot be shown, as the entities are not defined there.
Unfortunately I could not test it, because the addon needs to be verified before my Firefox will run it.
> Fix for #147: Add strings to German translation

- src/modules/pass.js
- src/modules/preferences.js
Detects OS to provide "through shell" defaults for OS X (fixes #72).  Also works around a bug in pass (bug has been fixed upstream but still not released) where .gpg file extension is not stripped off correctly, which breaks this plugin.
> Better defaults for OS X

- docs/INSTALLATION.md
- src/host/install_host_app.sh
This commit changes the host app install script to download the host app and manifest files from GitHub instead of using files on disk.
As discussed in #169 , I feel like the install script should be very easy to run. This change enables a user to do one-liners like this to install the host app:
```
$ curl -sSL https://github.com/nwallace/passff/releases/download/1.0/install_host_app.sh | bash -s -- firefox
```
Note: Currently the script downloads the files from the master branch on GitHub. Before a release, we should update this to refer to a tag or release file in GitHub instead.
> Make install script easier to run

- docs/INSTALLATION.md
- src/host/install_host_app.bat
See #202.
This pull request adds a windows batch file to install the Host Application with the same (but only long -- parameters) as the bash script.
Files are installed to `C:\Users\USERNAME\AppData\Roaming\passff`. Next to the passff.py and passff.json which will either be downloaded or installed from the current directory, a `passff.bat` will be created with the following contents:
```
@ECHO OFF
SET "PATH=<value of PATH at the time of installation>"
SET "GNUPGHOME=<value of GNUPGHOMEat the time of installation>"
python "C:\Users\USERNAME\AppData\Roaming\passff\passff.py"  %*
```
Setting PATH this way is a necessity for python to be found in most windows installations, and if the installer file is called from a shell that has access to the `pass` command, that is already configured …
> create batch file for installation in windows

- src/modules/pass.js
The former version tried to split the target domain name using a string
`'.+'` which cannot be part of a domain name. It caused the generation
of a single group and the quality became trivial. The new version
matches domain names as intended.
The former code had a trivial result:
>>> hello.world".split('\.+')
Array [ "hello.world" ]
In contrast:
>>> hello.world".split(/\.+/)
Array [ "hello", "world" ]
> Fix computation of item quality

- src/modules/page.js
Hi. Unfortunately I have to use some web-pages that have two input fields of type password. 
passff will fill the password from the first line of the password file into **all** html input fields that have the password type - regardless of the presence of correct <other_inputfield_name>: <inputfield_value> lines. This is because isOtherInputCheck test for the loginInputTypes.
I removed this check and now the forms are filled correctly. I cannot see any side-effects. In fact, I do not understand why the other fields should only be text, email or tel inputs.
> remove input type checking from other fields

- src/_locales/de/messages.json
- src/_locales/en/messages.json
- src/_locales/ru/messages.json
- src/content/newPasswordWindow.html
- src/content/newPasswordWindow.js
- src/content/preferencesWindow.html
- src/modules/menu.js
- src/modules/pass.js
I just replaced `-` and `.` with `_`, which is the only symbol allowed.
This isn't sufficient to work in Chromium (#105). It still complains that 'browser is not defined'.
> Rename translation keys to be compatible with Chromium

- src/modules/page.js
Certain websites disable submit/login buttons until all necessary fields
have been filled in. This commit fires an input event on each field
whose value has been set to notify the website about the change.
> Improve support for forms that are not pure HTML and enhance submit button discovery

- src/modules/pass.js
This PR:
* Keeps a map of running execPass calls to prevent starving the gpg-agent with multiple overlapping requests for the same password. On my system, this dramatically reduces the number of duplicate passphrase prompts I receive.
* Suppresses the usual `window.alert` on `pass` failure when called from `getPasswordData`, which would fight with the gpg-agent passphrase dialog for focus and cause the UI to become unresponsive.
* Removes the infinite loop that caused passff to freeze the browser when the `No secret key` error occurs.
Tested against FF Nightly 59.0a1 (2017-11-19) (64-bit) on ArchLinux.
It is believed this PR will close #220, #243 and #101.
> Safer autofill

- src/modules/main.js
This PR is intended to close #225. 
As requested in that issue, this commit attempts future-proofing against the eventual solution to [the configurable keyboard shortcuts Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1215061). 
The central idea is to blur any focused text entry fields on `keydown` so they can't swallow the `keypress` that would otherwise trigger the passff UI. Most of the logic involved is in calculating what we're expecting the `keydown` event to look like based the browser.commands configuration. A smaller hardcoded version might look like this:
```javascript
document.addEventListener('keydown', (evt) => {
if ('y' == evt.key && evt.ctrlKey)
document.firstElementChild.focus();
});
```
Tested against FF Nightly 59.0a1 (2017-11-19) (64-bit) on ArchLinux.
> Add some DOM trickery to let the keyboard shortcut through, even when a password entry field is focused.

- src/skin/content.css
This adds a foreground-color to the popup menu, to make it readable if the default foreground color in Firefox is set to a light color.
Fixes issue #283.
Putting the color in `.passff_popup_menu *` did not do the trick, but `.passff_popup_menu button.passff_key span` suffices for me.
> Add foreground color to popup menu

- src/_locales/en/messages.json
Source: French translation (See PR #319  :+1: )
- Use a vocabulary closer to the user experience, and farther from the code, for eg:
- input | input fields | form > form (*field* is already used for the password data)
- root > all
- overwrite > replace
- Improve/Correct
- url > URL
- enter key > Enter key
- URL > tab's URL (more precise)
- *menu > *toolbar menu* or *form menu*
- symbols > special characters
- Maybe punctuations. 
- I don't know, tell me!
> [Discussion] Improve English translation

- src/modules/menu.js
- Do not truncate the error message, so that it can be entirely
selected with Ctrl+A or a triple click.
- Print error code before the error message, so that it is always
visible.
The error message might not be displayed entirely, does it introduce any bug/problem?
`[15:27:38] show -> gpg: decryption failed: No sec... (2)`
`[15:25:12] show -> (2) gpg: decryption failed: No secret key `
> Do not truncate error message in the statusbar

- src/_locales/de/messages.json
- src/_locales/en/messages.json
- src/_locales/fr/messages.json
- src/_locales/ru/messages.json
- src/content/preferences.html
Firstly, the current preferences can be a bit misleading. Indeed, the 'Autofilling' section groups options that do not require Autofilling at all:
- Mark fillable input fields with the PassFF icon
- Submit when selected via the input menu
- Password input names
- Login input names
Secondly, the terminology of PassFF is tricky: "field" stands for 'a field in a password file' and for 'an input field'. Therefore, a description is added to explain the terminology.
The commit also creates all relevant translation entries in French, German and Russian.
> Add an 'Inputs' section in the preferences

- src/modules/page.js
Input fields with the style '-moz-appearance: window' hide the PassFF icon.
Minimal Working Example
- copy-paste the HTML code below in a HTML file
- open it with Firefox
```
<html>
<head>
<meta charset="utf-8" />
</head>
<body>
<input name="login" type="text" style="-moz-appearance:window;">
</body>
</html>
```
I have also included `-webkit-appearance:none` for the other browsers (anticipating the chrome port...).
Tested on:
* Firefox 52 ESR and Firefox 61.0b13 Dev Edition.
* Linux Debian Stretch
> Fix invisible input menu's icon

- src/modules/menu.js
Commit https://github.com/passff/passff/commit/26f935923cc0fc9ffa163e71472c972166698605 broke a link in PassFF.
I randomly found it and fixed it :+1: 
The anchor `#installation`has no effect though.
> Fix dead link to PassFF's installation steps

- src/modules/pass.js
- src/modules/util.js
See https://github.com/passff/passff-host/issues/18
To be able to bugfix the host app without touching PassFF, we have to enforce *semantic versioning* in passff-host.
As a result, PassFF should more loosely check passff-host's version.
Note: The lexicography check requires its operands to be `string`s. Thus, I explicitly coerce `version` to be a `string`.
Let the user know that new versions of passff-host are available.
This will be the object of another PR.
> Check host app version by semantic versioning

- src/modules/page.js
I've noticed a bug with the (P) popup. Currently, only the z-index of the parent elements are checked, but not of elements nearby (which the popup may overlap). On amazon.de's login page for example they set the 'Anmelden' (login) button to z-index:20, but our popup only has the default z-index of 1. 
This patch uses querySelectorAll to filter through all z-indices and gives the popup the highest found. 
Is there a reason the addon only checked the parents? performance, maybe?
> fix z-index issue on e.g. amazon.de login

- src/content/passwordGenerator.html
- src/modules/pass.js
The additional info is added to the new pass entry right after creating
it in a separate step because `pass generate` has no option to append
data to the generated password during creation.
This PR is heavily based on the work by @eklitzke in #335. This PR is a (from my point of view) improved version that I hope will be merged rather than linger around without activity. I am new to JS and Firefox plugin development. So any feedback, both regarding functionality and style, is greatly appreciated.
I felt that allowing any additional data has many advantages over two very specific fields:
* Users can choose and use their own naming scheme
* Users can add more than only two rows
* This greatly reduces the code complexity because we now can reuse the `addNewPassword` directly.
> Prompt for additional info on generate

- src/modules/page.js
This will fix filling of OTP pin on Gitea server login page.
Gitea changed its OTP input login page in this commit
https://github.com/go-gitea/gitea/commit/03d6bab64373e883beb6f4867432ad4f12112950
> Fix OTP pin entry when input type is number

- src/_locales/en/messages.json
- src/content/preferences.html
- src/modules/pass.js
- src/modules/preferences.js
There are many situations in which a single pass entry corresponds to multiple completely different web urls. One way of handling this is to list all the urls a password corresponds to inside the password entry using an `url: ` meta tag. However, this is currently not supported by passff (#374). 
In the linked issue, the possibility of using `pass grep` to find these meta urls was discussed. This would generally require decrypting the entire password store on every login, which might be acceptable for some password stores with fast hardware, but probably not a very good experience when using for example a smartcard to decrypt.
What I'm instead proposing in this PR is to only decrypt the entire store once on the initial load of the addon and to create a `Map` of all meta urls contained in …
> Index all password store meta urls on passff init

- README.md
- src/modules/pass.js
This enhances OTP support by implementing hierarchical style based file structure OTP. This has the same requirements as #384: [pass-otp](https://github.com/tadfisher/pass-otp) extension, and [passff-host #33](https://github.com/passff/passff-host/pull/33) version >1.1.0
> Add OTP support for hierarchical based style

- src/modules/page.js
This fixes #417 for me on 71.0b3 (64-bit) macos.
> Fix Array.concat usage

- src/modules/pass.js
The pass-ff helper builds the regExp by concatenating by `|`
and adding `^(` in front and `):` at the back. The extension
only checked `/^(url|host):/` (case-sensitive). We now do a
case-insensitive match using the configured fields, falling
back to url|host if it is the empty array.
I'm not sure if the fallback is needed (I did not go trough all the code, maybe indexing should just stop if there are no `urlFieldNames`, maybe this is always set)
(Works on my machine)
> PassFF.Pass: use urlFieldNames in indexMetaUrls

- src/_locales/de/messages.json
- src/_locales/en/messages.json
- src/_locales/fr/messages.json
- src/_locales/pl/messages.json
- src/content/preferences.html
- src/modules/menu.js
- src/modules/preferences.js
- src/skin/menu.css
Implements #441
Implements various new behaviors on Enter key, and allow to configure Shift-Enter and Ctrl-Enter too. Shift-Enter was set to open in a new tab when the behavior was *go to* and it is still the default behavior but it is now configurable.
> Allow to configure alternate Enter key behavior

- src/modules/page.js
such as Gmail's search bar.
Another issue that I noticed (which is solved by this PR in gmail's case, but might be present elsewhere), is that with the current version of passff, the pass icon on the gmail search bar is repeated (`background` attribute is set to `repeat`):
> Skip inputs with placeholder containing `search`

- src/modules/auth.js
This change prevents from opening a large number of popups for embedded
objects requiring HTTP Auth (e.g., public or cached page data).
We do so by searching the currentAuths array for existing entries that
share the same Root URI and the same realm. If one is found, we don't
open a new popup, but return the Promise associated with the first auth
instead.
fixes: #343, #322
Signed-off-by: Olivier Mehani <shtrom@ssji.net>
> HTTP Auth: limit the number of popups

- src/modules/preferences.js
login.microsoftonline.com: `otc`
gitlab.com: `user[otp_attempt]`
> adding otp name defaults for microsoft and gitlab

- src/modules/pass.js
There is a bug where the top level view is enforced instead of the contextual view. This will occur when the field “Regex for hiding items” is empty (or only empty lines). Empty regex's will always pass Regex.test(). So, all items will be hidden, which is obviously not intended behavior.
I think I fixed it, but embarrassingly enough, I have trouble building and installing the extension (and so my patch) to test it. If someone could give some instructions, I would like to test it any ways.
> Bugfix: you can now leave regex for hiding items empty.

- src/modules/page.js
OTPs are often challenged on a new page after the username and password was entered. This change allows this workflow.
This should not impose additional security risks given that OTPs are:
* only valid for a short amount of time
* only valuable in combination with an identity (e.g. login, session, ...)
> Autofill lonely OTP inputs
