src/bootstrap.js

For me the add-on only works with this change.

Fix doubled menubar entry

---

src/modules/menu.js
src/modules/pass.js

This change appends / characters to directories in the entry list. I also took the liberty of making a proper constructor for the item object and cleaning up the createItemsMenuList function.

Display directories more clearly & small code cleanup

---

src/modules/preferences.js

when using "through shell" mode

add --login as default parameter

---

src/modules/menu.js

Compact view for refresh and options buttons

Compact view

---

src/chrome/locale/en-US/preferences.dtd

I was going through a german translation and some things don't really make sense. Here's a fix.

minor fixes in english translation

---

CONVENTIONS.md
src/.jshintrc
src/bootstrap.js
src/modules/common.js
src/modules/menu.js
src/modules/page.js
src/modules/pass.js
src/modules/preferences.js

Lots of changes, testing is encouraged.
The most important things to note are:
1. I added a few jshint annotations and a .jshintrc. If your editor supports jshint, using it is encouraged.
2. I removed the license header in ```bootstrap.js```. Since I found what I believed to be the original source file and saw that it had massively changed since then, I don't think the license header is necessary anymore.
3. Please, please use jshint. It will help avoid mistakes like the one fixed in 58c5a82.
I did a few tests with these changes applied and didn't notice anything massively broken. It would probably be a good idea to introduce a few test cases to prevent regressions, though.

Add JS code conventions, reformat source code to comply, general code cleanup

---

src/chrome/content/preferencesWindow.xul
src/chrome/locale/en-US/preferences.dtd
src/modules/menu.js
src/modules/preferences.js

This addresses #125. Unfortunately I do not know how to translate to Russian or German. It looks like there are multiple ways to do some things (e.g. fill and submit), so I picked the method that works best. There may be a better way to do this than using the switch statement, I'm open to suggestions!

Add option for setting default behavior of pressing enter key

---

src/modules/page.js
src/modules/pass.js

Allows for filling out inputs found in passwordData, which isn't login, password or url.

Autofill for other inputs

---

src/chrome/content/preferencesWindow.xul
src/modules/menu.js

Fixes #163 
Sorry about the extra stuff in the diff -- apparently my editor replaced some tab characters with spaces in menu.js.  If you want me to undo that, I can

Add option to go to URL & fill without submitting for enter key behavior

---

src/bootstrap.js
src/chrome/content/newPasswordWindow.xul
src/chrome/content/preferencesWindow.xul
src/chrome/locale/en-US/newPassword.dtd
src/chrome/locale/en-US/preferences.dtd
src/chrome/locale/en-US/strings.properties
src/chrome/skin/newPassword.css
src/modules/menu.js
src/modules/pass.js
src/modules/preferences.js

This lets you add passwords right from the extension. You can specify the password yourself, or generate one. After the new password is added, the password list will be refreshed so that the user can find it in the extension.  Some new preferences let you specify your preferred default settings for adding new passwords.

Add passwords

---

src/chrome/locale/ru-RU/preferences.dtd

Updated russian translation's dtd

---

src/Makefile
src/host/install_host_app.bat
src/host/install_host_app.sh
src/manifest.json

Following https://github.com/passff/passff/pull/287

Use a default dummy version name

---

src/modules/page.js

fix the PR https://github.com/passff/passff/pull/287 :-1: 
Tested with the (id=nl_email, name=e) input field on https://www.qantas.com/fflyer/dyns/LoginForm

fix: LowerCase input's name & id, fix #280

---

src/modules/page.js

fixes #278 
I haven't tested this too much, since I'm not really a javascript developer, but it *works on my machine!™*

disable autocompletion while popup is open

---

src/_locales/de/messages.json
src/_locales/en/messages.json
src/content/preferences.html
src/modules/preferences.js
src/modules/util.js

implements / fixes #297
* logging now disabled by default
* I do not know russian, so I haven't touched the `ru/` file. 
Side Note: when can we expect a new release (especially with the PR #281 merged)?

make logging optional (toggle in preferences)

---

src/_locales/fr/messages.json

@tuxor1337 
Could you keep the PR opened please? Maybe some *baguettes* will want to contribute :)
I have been quite liberal while translating and this PR made me dive into the English translation. Therefore, I propose some improvements to the English translation. (See PR #318)
---
There is a double-space `␣␣` somewhere in the German translation. Happy finding!

[Discussion] Add French translation

---

src/modules/menu.js

Nothing fancy.
`[16:15:10] ls -> (0)` <- awkward? 
`[16:12:24] ls -> no error message (0)`

Print by default 'no error msg' in the statusbar

---

src/_locales/en/messages.json

This fixes a minor grammar issue.

Fix a minor typo (specials -> special)

---

src/_locales/ru/messages.json

Finish russian transtaltion.

---

Makefile
docs/CONTRIBUTING.md

Signed-off-by: Olivier Mehani <shtrom@ssji.net>

Move Makefile to root

---

README.md
docs/ISSUE_TEMPLATE.md
src/modules/main.js
src/modules/page.js
src/modules/pass.js
src/modules/preferences.js

Instead of silently pushing these small changes to master, I prefer to open en PR for better scrutiny and transparency ;)
312e041 Doc: Improve the guide to install a pinentry prog
ac66b4c Doc: Add Contributing section
84c1fe2 Add error message "Failed to execute host app"
c1e740d Doc: Correct browser compatibility
9a0b4ce fix: ParseInt explicitly uses base 10
1bfbffd ISSUE_TEMPLATE: Add pass & web console outputs

Misc improvements: Mostly to the documentation, except a new error message and a fix for parseInt()

---

README.md
src/_locales/en/messages.json
src/content/preferences.html
src/modules/main.js
src/modules/page.js
src/modules/pass.js
src/modules/preferences.js

This provides support for [pass-otp](https://github.com/tadfisher/pass-otp) and resolves #200 however it requires [passff-host #33](https://github.com/passff/passff-host/pull/33) to be updated as well.
:city_sunrise:

OTP support

---

docs/ISSUE_TEMPLATE.md

Clarified issue template text

---

src/modules/pass.js

Assume 'testing' is valid for otp, see #387 #389

---

src/modules/preferences.js

In my tests, this fixes #397. Please confirm!

Prefs: Get shortcut from browser.commands, fix #397

---

src/_locales/pl/messages.json

Hello. This is my first contribution to open-source community. I translated extension to Polish. I hope that everything is okay. Please let me know if I made something wrong

Polish translation

---

README.md
src/_locales/en/messages.json
src/content/preferences.html
src/modules/pass.js
src/modules/preferences.js

The current implementation is just a blacklist, but I imagine it could
easily be extended to being a whitelist based on a toggle. If that is
desirable, the easiest way to do this would be to create a radio
button (checkbox might work as well, but would be less clear) and check
its state in `isHidden()`. If it is in blacklist mode, `return match`.
Else, `return !match`. Easy inversion.
I'm completely unfamiliar with JS, so if anything could be achieved in a
more concise manner, please feel free to tell me and I'll fix it right up.
---
Might fix #401

Implement blacklisting of specific files/folders

---

src/_locales/pt/messages.json

Adds pt_br (or simply pt) locale

Add Brazilian Portuguese translation

---

docs/CONTRIBUTING.md
src/skin/content.css
src/skin/menu.css
src/skin/preferences.css

I also updated `CONTRIBUTING.md` - feel free to edit / revert if not helpful!
I also saw the 2-space guideline, but matched style in `preferences.css` for initial review - happy to reformat the file if desired.
Thanks!

Add a minimal-delta dark mode style

---

src/_locales/zh/messages.json

Adds zh (simplified chinese) locale

Add locales: simplified chinese
